# Generated by Django 3.0.7 on 2021-11-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping',
            field=models.BooleanField(default=True),
        ),
    ]
