# Generated by Django 3.2 on 2021-10-18 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TemplateApp', '0001_add_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 2, 36, 7, 250703, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 2, 36, 7, 250760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
