# Generated by Django 3.2 on 2021-10-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_schools_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('age',), 'verbose_name_plural': '生徒'},
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=20, verbose_name='学校名'),
        ),
    ]
